export default  [
    { src: "/frontend/node_modules/jquery/dist/jquery.min.js" },
    { src: "/frontend/node_modules/popper.js/dist/umd/popper.min.js" },
    { src: "/frontend/node_modules/bootstrap/dist/js/bootstrap.min.js" },
    { src: "/frontend/node_modules/headroom.js/dist/headroom.min.js" },
    { src: "/frontend/node_modules/onscreen/dist/on-screen.umd.min.js" },
    { src: "/frontend/node_modules/nouislider/distribute/nouislider.min.js" },
    { src: "/frontend/node_modules/bootstrap-datepicker/js/bootstrap-datepicker.js" },
    { src: "/frontend/node_modules/bootstrap-tagsinput/dist/bootstrap-tagsinput.min.js" },
    { src: "/frontend/node_modules/waypoints/lib/jquery.waypoints.min.js" },
    { src: "/frontend/node_modules/owl.carousel/dist/owl.carousel.min.js" },
    { src: "/frontend/node_modules/jarallax/dist/jarallax.min.js" },
    { src: "/frontend/node_modules/jquery.counterup/jquery.counterup.min.js" },
    { src: "/frontend/node_modules/jquery-countdown/dist/jquery.countdown.min.js" },
    { src: "/frontend/node_modules/smooth-scroll/dist/smooth-scroll.polyfills.min.js" },
    { src: "/frontend/node_modules/chartist/dist/chartist.js" },
    { src: "/frontend/node_modules/chartist-plugin-tooltips/dist/chartist-plugin-tooltip.min.js" },
    { src: "/frontend/node_modules/prismjs/prism.js" },
    { src: "/frontend/node_modules/jqvmap/dist/jquery.vmap.min.js" },
    { src: "/frontend/node_modules/jqvmap/dist/maps/jquery.vmap.world.js" },
    { src: "/frontend/assets/js/leaf.js" }
];
